#!/usr/bin/env bash

set -ex

GOOS=windows GOARCH=amd64 go build -o build/windows-amd64 ./...
GOOS=linux GOARCH=amd64 go build -o build/linux-amd64 ./...
GOOS=linux GOARCH=arm64 go build -o build/linux-arm64 ./...
GOOS=darwin GOARCH=amd64 go build -o build/darwin-amd64 ./...
